// This file is autogenerated by hyperschema-c
// !!DO NOT EDIT!!

#include "hc_schema.h"

int
hc_tree_node_preencode (compact_state_t *state, const hc_tree_node_t *value)
{
  int err;
  if ((err = compact_preencode_uint(state, value->index)) < 0) return err;
  if ((err = compact_preencode_uint(state, value->size)) < 0) return err;
  if ((err = compact_preencode_fixed32(state, value->hash)) < 0) return err;
  return 0;
}

int
hc_tree_node_encode (compact_state_t *state, const hc_tree_node_t *value)
{
  int err;
  if ((err = compact_encode_uint(state, value->index)) < 0) return err;
  if ((err = compact_encode_uint(state, value->size)) < 0) return err;
  if ((err = compact_encode_fixed32(state, value->hash)) < 0) return err;
  return 0;
}

int
hc_tree_node_decode (compact_state_t *state, hc_tree_node_t *result)
{
  int err;
  if ((err = compact_decode_uint(state, &result->index)) < 0) return err;
  if ((err = compact_decode_uint(state, &result->size)) < 0) return err;
  if ((err = compact_decode_fixed32(state, result->hash)) < 0) return err;
  return 0;
}

void
hc_tree_node_destroy (hc_tree_node_t *result)
{
}
