// This file is autogenerated by hyperschema-c
// !!DO NOT EDIT!!
// Schema Version: 1

#ifndef HC_SCHEMA_H
#define HC_SCHEMA_H

#include <compact.h>

// @hc/tree-node
typedef struct hc_tree_node_s {
  uint64_t index;
  uint64_t size;
  uint8_t hash[32];
} hc_tree_node_t;

int
hc_tree_node_preencode (compact_state_t *state, const hc_tree_node_t *value);

int
hc_tree_node_encode (compact_state_t *state, const hc_tree_node_t *value);

int
hc_tree_node_decode (compact_state_t *state, hc_tree_node_t *result);

void
hc_tree_node_destroy (hc_tree_node_t *result);

#endif // HC_SCHEMA_H
