// This file is autogenerated by hyperschema-c
// !!DO NOT EDIT!!
// Schema Version: 5

#ifndef HC_SCHEMA_H
#define HC_SCHEMA_H

#include <compact.h>
#include <stdbool.h>

// @hc/tree-node
typedef struct hc_tree_node_s {
  uint64_t index;
  uint64_t size;
  uint8_t hash[32];
} hc_tree_node_t;

int
hc_tree_node_preencode (compact_state_t *state, const hc_tree_node_t *value);

int
hc_tree_node_encode (compact_state_t *state, const hc_tree_node_t *value);

int
hc_tree_node_decode (compact_state_t *state, hc_tree_node_t *result);

void
hc_tree_node_destroy (hc_tree_node_t *result);

// @hc/head
typedef struct hc_head_s {
  uint64_t fork;
  uint64_t length;
  uint8_t root_hash[32];
  uint8_t *signature; /* borrows from decode buffer */
  size_t signature_len;
  bool has_timestamp;
  uint64_t timestamp;
} hc_head_t;

int
hc_head_preencode (compact_state_t *state, const hc_head_t *value);

int
hc_head_encode (compact_state_t *state, const hc_head_t *value);

int
hc_head_decode (compact_state_t *state, hc_head_t *result);

void
hc_head_destroy (hc_head_t *result);

// @hc/store-head
typedef struct hc_store_head_s {
  uint64_t cores;
  uint64_t datas;
  uint64_t groups;
  bool has_seed;
  uint8_t seed[32];
  bool has_default_discovery_key;
  uint8_t default_discovery_key[32];
} hc_store_head_t;

int
hc_store_head_preencode (compact_state_t *state, const hc_store_head_t *value);

int
hc_store_head_encode (compact_state_t *state, const hc_store_head_t *value);

int
hc_store_head_decode (compact_state_t *state, hc_store_head_t *result);

void
hc_store_head_destroy (hc_store_head_t *result);

// @hc/store-core
typedef struct hc_store_core_s {
  uint64_t core_ptr;
  uint64_t data_ptr;
} hc_store_core_t;

int
hc_store_core_preencode (compact_state_t *state, const hc_store_core_t *value);

int
hc_store_core_encode (compact_state_t *state, const hc_store_core_t *value);

int
hc_store_core_decode (compact_state_t *state, hc_store_core_t *result);

void
hc_store_core_destroy (hc_store_core_t *result);

// @hc/signer
typedef struct hc_signer_s {
  uint64_t signature;
  uint8_t namespace[32];
  uint8_t public_key[32];
} hc_signer_t;

int
hc_signer_preencode (compact_state_t *state, const hc_signer_t *value);

int
hc_signer_encode (compact_state_t *state, const hc_signer_t *value);

int
hc_signer_decode (compact_state_t *state, hc_signer_t *result);

void
hc_signer_destroy (hc_signer_t *result);

// @hc/prologue
typedef struct hc_prologue_s {
  uint8_t hash[32];
  uint64_t length;
} hc_prologue_t;

int
hc_prologue_preencode (compact_state_t *state, const hc_prologue_t *value);

int
hc_prologue_encode (compact_state_t *state, const hc_prologue_t *value);

int
hc_prologue_decode (compact_state_t *state, hc_prologue_t *result);

void
hc_prologue_destroy (hc_prologue_t *result);

// @hc/manifest
typedef struct hc_manifest_s {
  uint64_t version;
  bool allow_patch;
  uint64_t hash;
  uint64_t quorum;
  hc_signer_t *signers; /* array */
  size_t signers_len;
  bool has_prologue;
  hc_prologue_t prologue;
  bool has_linked;
  uint8_t (*linked)[32]; /* array of fixed32 */
  size_t linked_len;
  bool has_user_data;
  uint8_t *user_data; /* borrows from decode buffer */
  size_t user_data_len;
} hc_manifest_t;

int
hc_manifest_preencode (compact_state_t *state, const hc_manifest_t *value);

int
hc_manifest_encode (compact_state_t *state, const hc_manifest_t *value);

int
hc_manifest_decode (compact_state_t *state, hc_manifest_t *result);

void
hc_manifest_destroy (hc_manifest_t *result);

#endif // HC_SCHEMA_H
