// This file is autogenerated by hyperschema-c
// !!DO NOT EDIT!!
// Schema Version: 2

#ifndef HC_SCHEMA_H
#define HC_SCHEMA_H

#include <compact.h>
#include <stdbool.h>

// @hc/tree-node
typedef struct hc_tree_node_s {
  uint64_t index;
  uint64_t size;
  uint8_t hash[32];
} hc_tree_node_t;

int
hc_tree_node_preencode (compact_state_t *state, const hc_tree_node_t *value);

int
hc_tree_node_encode (compact_state_t *state, const hc_tree_node_t *value);

int
hc_tree_node_decode (compact_state_t *state, hc_tree_node_t *result);

void
hc_tree_node_destroy (hc_tree_node_t *result);

// @hc/head
typedef struct hc_head_s {
  uint64_t fork;
  uint64_t length;
  uint8_t root_hash[32];
  uint8_t *signature; /* borrows from decode buffer */
  size_t signature_len;
  bool has_timestamp;
  uint64_t timestamp;
} hc_head_t;

int
hc_head_preencode (compact_state_t *state, const hc_head_t *value);

int
hc_head_encode (compact_state_t *state, const hc_head_t *value);

int
hc_head_decode (compact_state_t *state, hc_head_t *result);

void
hc_head_destroy (hc_head_t *result);

#endif // HC_SCHEMA_H
